In [1]:
import pandas as pd

In [8]:
df_a = pd.read_csv(r'data\ADANIPORTS.NS.csv')

In [9]:
df_a.head()

,Price,Close,High,Low,Open,Volume,Ticker
0,Ticker,ADANIPORTS.NS,ADANIPORTS.NS,ADANIPORTS.NS,ADANIPORTS.NS,ADANIPORTS.NS,NaN
1,Date,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-01,364.3482971191406,365.8919473471767,353.10864266069,355.03819808506535,11377167,ADANIPORTS.NS
3,2020-01-02,369.6545715332031,371.14999464055313,363.2388056878108,364.63774513619,5919760,ADANIPORTS.NS
4,2020-01-03,369.0274963378906,370.8123410976035,365.843741479891,369.2204636686037,3684824,ADANIPORTS.NS

In [10]:
df_a.drop(index=[0,1],inplace=True)

In [11]:
df_a.head()

,Price,Close,High,Low,Open,Volume,Ticker
2,2020-01-01,364.3482971191406,365.8919473471767,353.10864266069,355.03819808506535,11377167,ADANIPORTS.NS
3,2020-01-02,369.6545715332031,371.14999464055313,363.2388056878108,364.63774513619,5919760,ADANIPORTS.NS
4,2020-01-03,369.0274963378906,370.8123410976035,365.843741479891,369.2204636686037,3684824,ADANIPORTS.NS
5,2020-01-06,366.8085021972656,374.3337566623756,361.55045182790013,374.3337566623756,12482680,ADANIPORTS.NS
6,2020-01-07,371.2464294433594,376.02209060723163,368.93096896253667,370.52284620293494,8091465,ADANIPORTS.NS

In [16]:
df_a.rename(columns={'Price':'Date'},inplace=True)

In [17]:
df_a.head()

,Date,Close,High,Low,Open,Volume,Ticker
2,2020-01-01,364.3482971191406,365.8919473471767,353.10864266069,355.03819808506535,11377167,ADANIPORTS.NS
3,2020-01-02,369.6545715332031,371.14999464055313,363.2388056878108,364.63774513619,5919760,ADANIPORTS.NS
4,2020-01-03,369.0274963378906,370.8123410976035,365.843741479891,369.2204636686037,3684824,ADANIPORTS.NS
5,2020-01-06,366.8085021972656,374.3337566623756,361.55045182790013,374.3337566623756,12482680,ADANIPORTS.NS
6,2020-01-07,371.2464294433594,376.02209060723163,368.93096896253667,370.52284620293494,8091465,ADANIPORTS.NS

In [18]:
df_a.isna().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
Ticker    0
dtype: int64